[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 1

# The default session, also known as the greeter.
[default_session]

command = "tuigreet --time --remember --asterisks --remember-session --sessions /usr/share/wayland-sessions --theme 'text=white;container=darkgray;border=cyan;greet=blue;prompt=green;input=white;button=yellow;title=red'"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "greeter"
