[background]
fit = "Fill"

[GTK]
application_prefer_dark_theme = true
theme_name = "Adwaita-dark"
icon_theme_name = "Adwaita"
cursor_theme_name = "Adwaita"
font_name = "MonaspiceNe Nerd Font 16"

[widget]
style = "/etc/greetd/regreet.css"

[commands]
reboot = ["systemctl", "reboot"]
poweroff = ["systemctl", "poweroff"]
